[TASK-64] backend-prepare
GregorioFornetti/little-fuck pull request #23
Opened 2024-06-01 16:22 UTC by GregorioFornetti

2024-06-03 21:44 UTC, lauanS requested changes
Algumas mudanças relacionadas a pequenos erros de digitação/escrita e import

2024-06-03 21:44 UTC, lauanS commented on backend/src/events/match/functions/endMatch.ts
> +
Adicionar importação do tipo `Player`

```suggestion
import Player from "../../../interfaces/Player";

```

2024-06-03 21:44 UTC, lauanS commented on backend/src/events/match/functions/endSpecialMatch.ts
> +
Adicionar importação do tipo `Player`
```suggestion
import Player from "../../../interfaces/Player";

```

2024-06-03 21:44 UTC, lauanS commented on backend/src/events/round/functions/endRound.ts
> +
Último caso de importação do tipo `Player`

```suggestion
import Player from "../../../interfaces/Player";

```

2024-06-03 23:51 UTC, GregorioFornetti commented
Acho que nas minhas revisões eu só comentava e não sugeria alterações a serem feitas...
Irei fazer o mesmo que vc fez aqui para os próximos PRs que eu for revisar. Thx

2024-06-04 14:54 UTC, lauanS approved these changes

2024-06-04 14:56 UTC, merged