[TASK-14] player-join
GregorioFornetti/little-fuck pull request #4
Opened 2024-05-11 18:45 UTC by lauanS

2024-05-11 20:43 UTC, GregorioFornetti requested changes

2024-05-11 20:43 UTC, GregorioFornetti commented on frontend/src/__tests__/events/lobby/testHandlePlayerJoin.ts
> +    handleJoinLobbySuccess(lobbyParam)
Acho que seria melhor "settar" o lobby diretamente, para não depender da função `handleJoinLobbySuccess`.
Caso a função `handleJoinLobbySuccess` pare de funcionar, os testes aqui falhariam também.

2024-05-11 20:43 UTC, GregorioFornetti commented on frontend/src/__tests__/events/lobby/testHandlePlayerJoin.ts
> +    handleJoinLobbySuccess(lobbyParam)
Mesma coisa aqui

2024-05-11 20:43 UTC, GregorioFornetti commented on frontend/src/__tests__/events/lobby/testHandlePlayerJoin.ts
> +    handleJoinLobbySuccess(lobbyParam)
Mesma coisa aqui

2024-05-12 05:15 UTC, lauanS commented
Aproveitei para atualizar a branch com as mudanças da main e melhorar outros aspectos dos casos de teste também

2024-05-12 15:59 UTC, GregorioFornetti approved these changes
Perfeito =D

2024-05-12 15:59 UTC, merged